outil/urls.py
'''

Copyright ou © ou Copr. Cerema, (novembre 2017) 

www.cerema.fr

Ce logiciel est un programme informatique facilitant la mise en oeuvre
de la méthodologie d’estimation territorialisée des besoins en logements 
conçue par la direction de l’Habitat de l’Urbanisme et des Paysages du 
ministère du Logement et de l’Habitat durable, en partenariat avec le 7
Service de l’Observation et des Statistiques du CGDD et le Cerema.

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.

'''

from django.conf.urls import url

from .views import configuration
from .views import resultat

urlpatterns = [
    url(r'^accueil$', configuration.accueil, name='accueil'),
    url(r'^init$', configuration.initialisation, name='initialisation'),
    url(r'^init_classe$', configuration.initialisation_classe, name='initialisation_classe'),
    url(r'^init_commune$', configuration.initialisation_commune, name='initialisation_commune'),
    url(r'^save$', configuration.sauvegarde, name='sauvegarde'),
    url(r'^load$', configuration.chargement_config, name='chargement'),
    url(r'^b11$', configuration.b11, name='brique_1_1'),
    url(r'^b12$', configuration.b12, name='brique_1_2'),
    url(r'^b13$', configuration.b13, name='brique_1_3'),
    url(r'^b14$', configuration.b14, name='brique_1_4'),
    url(r'^b15$', configuration.b15, name='brique_1_5'),
    url(r'^b16$', configuration.b16, name='brique_1_6'),
    url(r'^b17$', configuration.b17, name='brique_1_7'),
    url(r'^b1-ventilation$', configuration.b1_ventilation, name='voletB1_ventilation'),
    url(r'^b21$', configuration.b21, name='brique_2_1'),
    url(r'^b22$', configuration.b22, name='brique_2_2'),
    url(r'^b_resorption$', configuration.b_resorption, name='voletB_resorption'),
    url(r'^c_classe_commune$', configuration.c_classe_commune, name='classe_commune'),
    url(r'^synthese_ze$', resultat.synthese_zone_emploi, name='synthese_ze'),    
    url(r'^resultat_par_ze$', resultat.resultat_par_ze, name='resultat_par_ze'),
    url(r'^export_ze$', resultat.export_ze, name='export_ze'), 
    url(r'^synthese_epci$', resultat.synthese_epci, name='synthese_epci'),
    url(r'^resultat_par_epci$', resultat.resultat_par_epci, name='resultat_par_epci'),
    url(r'^export_epci$', resultat.export_epci, name='export_epci'),      
]

tpl_outil/urls.py
'''

Copyright ou © ou Copr. Cerema, (novembre 2017) 

www.cerema.fr

Ce logiciel est un programme informatique facilitant la mise en oeuvre
de la méthodologie d’estimation territorialisée des besoins en logements 
conçue par la direction de l’Habitat de l’Urbanisme et des Paysages du 
ministère du Logement et de l’Habitat durable, en partenariat avec le 7
Service de l’Observation et des Statistiques du CGDD et le Cerema.

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.

'''

from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from outil.views import configuration

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', configuration.accueil, name='start'),
    url(r'^tpl/', include('outil.urls', namespace='outil')),
]

outil/views/configuration.py
'''

Copyright ou © ou Copr. Cerema, (novembre 2017) 

www.cerema.fr

Ce logiciel est un programme informatique facilitant la mise en oeuvre
de la méthodologie d’estimation territorialisée des besoins en logements 
conçue par la direction de l’Habitat de l’Urbanisme et des Paysages du 
ministère du Logement et de l’Habitat durable, en partenariat avec le 7
Service de l’Observation et des Statistiques du CGDD et le Cerema.

Ce logiciel est régi par la licence CeCILL soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL, et que vous en avez accepté les
termes.

'''

import os
import time
from django.db import transaction
from django.shortcuts import render
from django.shortcuts import redirect
from outil.models import ParametreZE
from outil.models import Commune
from outil.initialisation.charger_bdd import init_bdd
from outil.initialisation.charger_bdd import init_classe_communes
from outil.initialisation.charger_bdd import init_communes
from outil.initialisation.params import REPERTOIRE_SAUVEGARDE
from outil.calcul.calculs_ze import CalculZE

@transaction.atomic
def initialisation(request):
    """
    Vue permettant la réinitialisation de la base de données de paramètrage
    """
    init_bdd()
    message_succes = 'Paramètrages (volet B) réinitialisés'
    return render(request, 'succes.html', locals())

@transaction.atomic
def initialisation_classe(request):
    """
    Vue permettant la réinitialisation des classes de commune dans la base de données
    """
    init_classe_communes()
    message_succes = 'Classes communales (volet C) réinitialisées'
    return render(request, 'succes.html', locals())

def initialisation_commune(request):
    """
    Vue permettant la réinitialisation des communes/EPCI
    """
    init_communes()
    message_succes = 'Communes et EPCI associés réinitialisés'
    return render(request, 'succes.html', locals())

def sauvegarde(request):
    """
    Vue permettant la sauvegarde du paramétrage dans un fichier .cfg (voire .cfgclass)
    Le répertoire de sauvegarde est défini dans la variable REPERTOIRE_SAUVEGARDE
    """
    message_erreur = None
    if request.method == 'POST':
        try:
            fichier = 'save_config_{0}.cfg'.format(time.strftime('%Y_%m_%d_%H%M%S'))
            chemin_fichier = os.path.join(REPERTOIRE_SAUVEGARDE, fichier)
            description = request.POST['description']
            ParametreZE.objects.sauvegarder(chemin_fichier, description)
            message_succes = 'Configuration des paramètres sauvegardée dans {0} avec la description : {1}'.format(fichier, description)
            if Commune.objects.classes_modifiees:
                fichier_modif_classe = fichier.replace('.cfg', '.cfgclass')
                chemin_fichier_modif_classe = os.path.join(REPERTOIRE_SAUVEGARDE, fichier_modif_classe)
                Commune.objects.sauvegarder(chemin_fichier_modif_classe)
                message_succes += '</p><p>Modification des classes communales sauvegardée dans {0}'.format(fichier_modif_classe)
            return render(request, 'succes.html', locals())
        except Exception as e:
            print(e)
            message_erreur = 'Impossible de sauvegarder la configuration.'
    return render(request, 'sauvegarde_config.html', locals())

@transaction.atomic
def chargement_config(request):
    """
    Vue permettant le chargement ou la suppression du paramétrage depuis un fichier .cfg (voire .cfgclass)
    Le répertoire de sauvegarde est défini dans la variable REPERTOIRE_SAUVEGARDE
    """
    message_erreur = None
    if request.method == 'POST':
        if 'load' in request.POST:
            chemin_fichier = os.path.join(REPERTOIRE_SAUVEGARDE, request.POST['fichier'])
            try:
                ParametreZE.objects.charger(chemin_fichier)
                message_succes = 'Configuration des paramètres chargée'
                chemin_fichier_modif_classe = chemin_fichier.replace('.cfg', '.cfgclass')
                if os.path.exists(chemin_fichier_modif_classe):
                    Commune.objects.charger(chemin_fichier_modif_classe)
                    message_succes += '</p><p>Modification des classes communales chargée'
                else:
                    init_classe_communes()
                    message_succes += "</p><p>Fichier de modification des classes communales inexistant. Les classes par défaut ont été affectées." 
                return render(request, 'succes.html', locals())
            except Exception as e:
                print(e)
                message_erreur = 'Impossible de charger le fichier {0}'.format(chemin_fichier)
        elif 'delete' in request.POST:
            try:
                chemin_fichier = os.path.join(REPERTOIRE_SAUVEGARDE, request.POST['fichier'])
                if os.path.exists(chemin_fichier):
                    os.remove(chemin_fichier)
                chemin_fichier_modif_classe = chemin_fichier.replace('.cfg', '.cfgclass')
                if os.path.exists(chemin_fichier_modif_classe):
                    os.remove(chemin_fichier_modif_classe)
            except Exception as e:
                print(e)
                message_erreur = 'Impossible de supprimer la configuration'
    fichiers_config = [(fichier, 
                        ParametreZE.objects.description(os.path.join(REPERTOIRE_SAUVEGARDE, fichier))) for fichier in os.listdir(REPERTOIRE_SAUVEGARDE) if fichier.endswith('.cfg')]        
    return render(request, 'chargement_config.html', locals())

'''

REDIRECTIONS

'''


REDIRECTION_SUIVANTE = {'/tpl/b11': 'outil:brique_1_2',
                        '/tpl/b12': 'outil:brique_1_3',
                        '/tpl/b13': 'outil:brique_1_4',
                        '/tpl/b14': 'outil:brique_1_5',
                        '/tpl/b15': 'outil:brique_1_6',
                        '/tpl/b16': 'outil:brique_1_7',
                        '/tpl/b17': 'outil:voletB1_ventilation',
                        '/tpl/b1-ventilation': '/tpl/b_resorption',
                        '/tpl/b_resorption': 'outil:brique_2_1',
                        '/tpl/b21': 'outil:brique_2_2',
                        '/tpl/b22': '/tpl/c_classe_commune',
                        }

'''

Fonction de traitement du POST

'''

def traitement_post(post, form_analyse, besoin_validation = False):
    message_erreur = None
    if 'next' in post:
        return message_erreur, True
    form = form_analyse(post)
    if besoin_validation:
        success, message_erreur = form.is_valid()
    if not message_erreur:
        form.modifier_parametres()
        #if 'save_and_next' in post:
        #    return message_erreur, True 
    return message_erreur, False
    

'''

Classe pour l'analyse des formulaires

'''

class FormAnalyse:
    
    def __init__(self, post):
        self.post = post
    
    def choix_mono_multi(self, type):
        if 'choix-{0}-mono-multi'.format(type) in self.post:
            return self.post['choix-{0}-mono-multi'.format(type)]
        return None

    def valeur_radio_multi(self, type):
        if 'multi-{0}-ze'.format(type) in self.post:
            return self.post['multi-{0}-ze'.format(type)]
        return None
    
    def boolean_radio_multi(self, type, valeur):
        if 'multi-{0}-ze'.format(type) in self.post:
            return True if self.post['multi-{0}-ze'.format(type)] == valeur else False
        return None
    
    def dictionnaire_radio_mono(self, prefixe):
        '''
        Dictionnaire : 
            - clef : code ZE
            - valeur : valeur retournee par le formulaire pour la valeur prefixe + code ZE
        '''
        prefixe = 'mono-{0}-ze'.format(prefixe)
        parametres = {k[len(prefixe):]: v for k, v in self.post.items() if k.startswith(prefixe)}
        if len(parametres) == 0:
            return {}
        return parametres
    
    def dictionnaire_boolean_radio_mono(self, prefixe, bool):
        prefixe = 'mono-{0}-ze'.format(prefixe)
        parametres = {k[len(prefixe):]: bool[v] for k, v in self.post.items() if k.startswith(prefixe)}
        if len(parametres) == 0:
            return {}
        return parametres
    
    def boolean_checkbox_multi(self, prefixe, suffixe):
        prefixe = 'multi-{0}-ze-'.format(prefixe)
        if prefixe + suffixe in self.post:
            return True
        return False
    
    def liste_checkbox_mono(self, prefixe, suffixe):
        '''
        Liste des codes ZE pour lesquels le critere est coché
        '''
        prefixe = 'mono-{0}-ze-'.format(prefixe)

outil/templates/accueil.html
{% extends 'principal.html' %}
{% load staticfiles %}
{% block body %}


<div class="jumbotron" style="background-color: transparent !important; background:url('{% static 'img/fond_1300.png' %}') no-repeat center center; background-opacity: 0.5; min-height: 100%; min-height: 70vh; display: flex; align-items: center;">
  <div class="container-fluid">
  	<div style="margin:50px;"></div>
    <h1 style="color:#d34615;" class="text-center"><b><i class="fa fa-home" aria-hidden="true"></i> Otelo</b></h1>
    <p class="text-center">Outil pour la territorialisation de la production de logements</p>
    <div style="margin:120px;"></div>
  	<p class="text-center"><a class="btn btn-info btn-lg" href="{% url 'outil:brique_1_1' %}" role="button">Commencer la configuration</a></p>
  	<div style="margin:130px;"></div>
  </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="text-muted">
        <p class="text-center"><img src="{% static 'img/ministere_logo.png' %}" height="70px">&nbsp;&nbsp;<img src="{% static 'img/cerema_logo.png' %}" width="100px"></p>
  		<p class="text-center">Version 1.2 - fév.2018</p>
        </p>
    </div>
</footer>

{% endblock %}

outil/templates/b12.html
{% extends 'principal.html' %}
{% block body %}

	<div class="page-header">
  		<h1><i class="fa fa-cubes" aria-hidden="true"></i> Ménages vivant dans un logement qui n'est pas le leur <small>Brique 1.2</small></h1>
	</div>
	
	<div class="panel panel-info">
  		<div class="panel-heading">Préambule</div>
  		<div class="panel-body"  align="justify">
  			<p>Les personnes vivant dans un logement qui n’est pas le leur sont définies comme étant les personnes se trouvant en situation de cohabitation subie. 
  			Elles sont regroupées en deux catégories :</p>
  			
  			<ul>
				<li>Les personnes logées chez un parent ou un enfant (cohabitation intergénérationnelle) ; 
				<li>Les personnes hébergées chez un tiers sans lien de parenté direct.
			</ul>
			
			<p><b>HEBERGES CHEZ UN TIERS</b></p>
			<p><u>Précision méthodologique sur les sources :</u></p>
			<p>Pour identifier les personnes hébergées chez un tiers sans lien de parenté direct, il est recommandé de recourir à la même source que celle qui a été mobilisée pour les personnes sans abris, 
			en habitations de fortune ou logées à l’hôtel de la brique 1.1.</p>
		</div>
	</div>
	
	{% if message_erreur %}
	<div class="panel panel-danger">
  		<div class="panel-heading">Erreur</div>
  		<div class="panel-body">			
			<p class="bg-danger">{{message_erreur}}</p>		
		</div>
	</div>
	{% endif %}


<div class="panel panel-default">
	<div class="panel-body">
  		

	<div class="lead text-primary">
  		<h3><i class="fa fa-cogs" aria-hidden="true"></i> Cohabitation intergénérationnelle présumée subie</h3>
	</div>

	<div class="panel panel-primary">
  		<div class="panel-heading">Choix de la prise en compte (donnée Filocom)</div>  		
  		<div class="panel-body">
  		
  		{% include 'form_radio.html' with type='cohab' multi=multi_cohab valeurs=valeurs_cohab %}
  		
  		{% include 'validation_form.html' %} 	
		
		</div>
	</div>
	


	</div>
</div>


<div style="margin:15px;"></div>

<div class="panel panel-default">
	<div class="panel-body">

	<div class="lead text-primary">
  		<h3><i class="fa fa-cogs" aria-hidden="true"></i> Cohabitation subie (hors cohabitation intergénérationnelle)</h3>
	</div>
	
	
	<div class="panel panel-primary">
		<div class="panel-heading">Choix des catégories prises en compte (donnée SNE)</div>  		
		<div class="panel-body">			
		
		{% include 'form_checkbox.html' with type='heberg' multi=multi_heberg valeurs=valeurs_heberg autre_valeur='autre_source_b12'%}	
		
		{% include 'validation_form.html' %}
		
		</div>
	</div>
	


	</div>
</div>

<div style="margin:15px;"></div>

{% include 'validation_all_form.html' %}	
	
{% endblock %}

{% block javascript %}
<script type="text/javascript">
	
$(function() {
	
	{% include 'js_gestion_mono_multi.html' with type='cohab' multi=multi_cohab %}	
	{% include 'js_gestion_mono_multi.html' with type='heberg' multi=multi_heberg %}
	
	{% include 'js_gestion_forms.html' %}	
    
});
	
</script>
{% endblock %}

outil/templates/b15.html
{% extends 'principal.html' %}
{% block body %}

	<div class="page-header">
  		<h1><i class="fa fa-cubes" aria-hidden="true"></i> Ménages en inadéquation physique<small> Brique 1.5</small></h1>
	</div>
	
	<div class="panel panel-info">
  		<div class="panel-heading">Préambule</div>
  		<div class="panel-body"  align="justify">
			<p>L’inadéquation physique des ménages avec leur logement est ici envisagée sous l’angle du surpeuplement (ou de la sur-occupation) sur le parc privé. </p>
			<p><u>Précision méthodologique sur les sources :</u></p>
			<p>La définition de l’INSEE du surpeuplement modéré ou accentué est basée sur le nombre de pièces du logement, le nombre de personnes du ménage, leur âge et leur sexe.</p>
<p>La définition de Filocom de la sur-occupation légère ou lourde fait intervenir la surface du logement et le nombre de personnes du ménage.</p>
<p>La population des ménages en situation de surpeuplement accentué (resp. de sur-occupation lourde) est une sous-population des ménages en situation de surpeuplement modéré (resp. de sur-occupation légère).</p>
		</div>
	</div>
	
	{% if message_erreur %}
	<div class="panel panel-danger">
  		<div class="panel-heading">Erreur</div>
  		<div class="panel-body">			
			<p class="bg-danger">{{message_erreur}}</p>		
		</div>
	</div>
	{% endif %}
	
<div class="panel panel-default">
	<div class="panel-body">

	<div class="lead text-primary">
  		<h3><i class="fa fa-cogs" aria-hidden="true"></i> Inadéquation Physique</h3>
	</div>

	<div class="panel panel-primary">
  		<div class="panel-heading">Choix de la source de données et du niveau de suroccupation</div>  		
  		<div class="panel-body">
  			
  		{% include 'form_radio.html' with type='source' multi=multi_source valeurs=valeurs_source %}
  		
  		{% include 'validation_form.html' %}
		
		</div>
	</div>
		

<div style="margin:15px;"></div>	
	
	<div class="panel panel-primary">
		<div class="panel-heading">Choix des catégories prises en compte</div>  		
		<div class="panel-body">			
		
		{% include 'form_checkbox.html' with type='categorie' multi=multi_categorie valeurs=valeurs_categorie autre_valeur=None %}
		
		{% include 'validation_form.html' %}  	
	
		</div>
	</div>

	</div>
</div>

<div style="margin:15px;"></div>

{% include 'validation_all_form.html' %}		
	
{% endblock %}

{% block javascript %}
<script type="text/javascript">
	
$(function() {
	
	{% include 'js_gestion_mono_multi.html' with type='source' multi=multi_source %}	
	{% include 'js_gestion_mono_multi.html' with type='categorie' multi=multi_categorie %}	

    {% include 'js_gestion_forms.html' %}	  
});
	
</script>
{% endblock %}

outil/templates/b21.html
{% extends 'principal.html' %}
{% block body %}

	<div class="page-header">
  		<h1><i class="fa fa-cubes" aria-hidden="true"></i> Evolutions démographiques<small> Brique 2.1</small></h1>
	</div>
	
	<div class="panel panel-info">
  		<div class="panel-heading">Préambule</div>
  		<div class="panel-body">
	  		<p>Les besoins liés aux évolutions démographiques sont définis comme les besoins liés à l’apparition ou la disparition de ménages sur le territoire.</p>
	  		<p>Trois phénomènes sont à l’œuvre dans l’évolution du nombre de ménages :</p>
	  		<ul>
  				<li>L’accroissement naturel de la population ;
  				<li>Le solde migratoire de la population ;
  				<li>Le desserrement des ménages.
  			</ul>
  			<p><u>Précision méthodologique sur les sources :</u></p>
	  		<p>Pour les zones de plus de 50 000 habitants, l’INSEE produit des projections démographiques à partir du recensement.</p>
	  		<p>Six scenarios d’évolution du nombre de ménages sont proposés à l’évaluateur :</p>
			<ul>
  				<li>le scenario « central » d’évolution de la population combiné au scenario « tendanciel » de cohabitation ;
				<li>le scenario « central » d’évolution de la population combiné au scenario « maintien » de cohabitation ;
				<li>le scenario « central » d’évolution de la population combiné au scenario « accélération » de cohabitation ;
				<li>le scenario « central » d’évolution de la population combiné au scenario « décélération » de cohabitation ;
				<li>le scénario « population haute » d’évolution de la population combiné au scenario « tendanciel » de cohabitation ;
				<li>le scénario « population basse » d’évolution de la population combiné au scenario « tendanciel » de cohabitation.
			</ul>
			<p>Par défaut, l’évolution projetée du nombre de ménages du scenario « central » d’évolution de la population combiné au scenario « tendanciel » de cohabitation est indiquée.</p>
			<p> Pour les zones  de moins de 50 000 habitants, l’INSEE ne produit pas de telles projections démographiques. 
			C’est l’évolution passée du nombre de ménages d’après le recensement qui est proposée en valeur par défaut.</p>
			
		</div>
	</div>
	
	{% if message_erreur %}
	<div class="panel panel-danger">
  		<div class="panel-heading">Erreur</div>
  		<div class="panel-body">			
			<p class="bg-danger">{{message_erreur}}</p>		
		</div>
	</div>
	{% endif %}

<div class="panel panel-default">
	<div class="panel-body">

	<div class="lead text-primary">
  		<h3><i class="fa fa-cogs" aria-hidden="true"></i> Evolutions démographiques</h3>
	</div>

	<div class="panel panel-primary">
  		<div class="panel-heading">Choix de la projection démographique (donnée Omphale)</div>  		
  		<div class="panel-body">
  			
		{% include 'form_select_omphale.html' with type='scenario' multi=multi_scenario valeurs=valeurs_scenario param=parametre_scenario %}  	
	
		{% include 'validation_form.html' %}	
		
		</div>
	</div>
	


	</div>
</div>

<div style="margin:15px;"></div>	

{% include 'validation_all_form.html' %}		
	
{% endblock %}

{% block javascript %}
<script type="text/javascript">
	
$(function() {
	
	{% include 'js_gestion_mono_multi.html' with type='scenario' multi=multi_scenario %}		
    
    {% include 'js_gestion_forms.html' %}	   
});
	
</script>
{% endblock %}

outil/templates/js_gestion_mono_multi.html
	{% if multi %}
        $('.multi-{{type}}-ze').show();
        $('.mono-{{type}}-ze').hide();
    {% else %}
    	$('.mono-{{type}}-ze').show();
        $('.multi-{{type}}-ze').hide();
    {% endif %}
    

    $('input[type=radio][name=choix-{{type}}-mono-multi]').change(function() {
        if (this.value == 'multi') {
            $('.multi-{{type}}-ze').show();
            $('.mono-{{type}}-ze').hide();
        }
        else if (this.value == 'mono') {
        	$('.mono-{{type}}-ze').show();
            $('.multi-{{type}}-ze').hide();
        }
    });
    
  

outil/templates/succes.html
{% extends 'principal.html' %}
{% block body %}

	<div class="panel panel-success">
  		<div class="panel-heading">Succès</div>
  		<div class="panel-body">
			<p>{{message_succes|safe}}</p>
		</div>
	</div>
	
{% endblock %}